name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Check Python syntax
        run: python -m compileall .

      - name: Run all Python files
        run: |
          for f in $(find . -name "*.py"); do
            echo "Running $f"
            python "$f"
          done
